version: '3.8'
services:
  web:
    image: node:16
    ports:
      - '8080:8080'
    volumes:
      - '.:/src'
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
    working_dir: /src
    command: sh -c "cd /src; yarn; yarn dev --host 0.0.0.0"
