name: build and test!

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Add yarn
        run: corepack prepare yarn@1.22.17 --activate

      - name: Build
        run: yarn

      - name: Type Checking
        run: yarn type-checking

      - name: Linting Typescript
        run: yarn linting:ts

      - name: Linting CSS
        run: yarn linting:css

      - name: Testing
        run: yarn test
